cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: 123
      secret-key: 123
    queue:
      uri: http://localhost:4566
      name: sample-queue.fifo

server:
  port: 8081
